checks:
    php:
        no_eval: false              # required for code generation
        duplication: false          # duplications are for performance optimizations
        no_error_suppression: false # @ symbol use is unavoidable in this case

filter:
    paths:
        - "src/"

    excluded_paths: # phpmd fatals
        - "src/Stub/Answer/Builder/Detail/GeneratorAnswerBuilderDetail.php"
        - "src/Stub/Answer/Builder/Detail/GeneratorAnswerBuilderDetailWithReturn.php"
        - "src/Stub/EmptyValueFactory.php"
