global_exclude_dirs:
    - test/fixture
    - test/src

rules:
    php.use_php_eval_function:
        enabled: false # required for code generation
    php.duplicated_code:
        enabled: false # duplications are for performance optimizations
    php.silenced_error:
        enabled: false # @ symbol use is unavoidable in this case
    php.object_parameter_not_type_hinted:
        enabled: false # deliberate to squeeze out more performance, however slight
    php.bad_mutator_method_name_for_boolean_property:
        enabled: false # code style disagreement
    php.interface_has_no_interface_suffix:
        enabled: false # code style disagreement
    php.neglected_tests:
        enabled: false # some test suites are deliberately not run
