language: php

php:
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: '7.0'
          env: ELOQUENT_BUILD_WEB=1

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-reqs
script: scripts/travis
after_script: scripts/travis-after

env:
    global:
        - ELOQUENT_PUBLISH_VERSION=7.0
        - secure: "Mc3vD6Dfe0vZNZUZ6U30r48RRjnvO/B3f22Uj+0cANp6Ql7HTtw/gquTPGa52ho7gKZYC9QuOxlV7LOBwI3N+lBJbYtLAiWruyRjQ2aFI3CdZPU53a4rPCODkYoz7jpLijUgH/GrzBRhCFUJzr3WsIPxob4IkqMAn5heS+3FqGk="

cache:
    directories:
        - $HOME/.composer

sudo: false
