language: php
php:
    - "5.3.3"
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - "hhvm"
install:
    - composer selfupdate --no-interaction
    - composer install --no-interaction --no-progress --ignore-platform-reqs
script: vendor/bin/phpunit
