language: php
php:
    - "5.3.3"
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - nightly
    - hhvm
matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true
install:
    - composer selfupdate --no-interaction
    - composer install --no-interaction --no-progress --ignore-platform-reqs
script: "ls test/suite | xargs -I % sh -c 'echo; echo Testing %...; echo; phpunit --stop-on-failure test/suite/%'"
sudo: false
