language: php

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: nightly
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
          env: HHVMPHP7=1
        - php: hhvm-3.18
          sudo: required
          dist: trusty
          group: edge
          env: HHVMPHP7=1
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
          env: HHVMPHP7=1
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
        - env: HHVMPHP7=1

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction
before_script:
  - if [[ "$HHVMPHP7" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
script: scripts/travis
after_script: scripts/travis-after
deploy:
    - provider: script
      script: make publish
      skip_cleanup: true
      on:
          php: '7.1'
          branch: master
    - provider: script
      script: make publish
      skip_cleanup: true
      on:
          php: '7.1'
          tags: true

env:
    global:
        - ELOQUENT_PUBLISH_VERSION=7.1
        - secure: "ZACO936IO20LK1BfiDoOVgy+1NpeghXM5vk+9p2kf/9VhithSqSOipoCj4KxasVjAYi2XMQjUNTsoAgLZc7yaHlBYVEZrHpMylzD6Hp9a9K56z/bPEZlPjjLRzbsYMtF1OzKormLOfJIt0aNyJfGcgdD2+uyRUvuL0+z+0toQro="

cache:
    directories:
        - $HOME/.composer

sudo: false
