language: php
php:
    - "5.3.3"
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - "hhvm"
    - "hhvm-nightly"
install: composer install
script: vendor/bin/phpunit --configuration phpunit.coverage.xml
